-- goals table
ALTER TABLE goals ADD COLUMN IF NOT EXISTS coach_viewed BOOLEAN DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS created_by_coach BOOLEAN DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS deleted_by_client BOOLEAN DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;

-- users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS coach_id BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS current_weight DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_weight DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS height_cm DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_level VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS primary_goal VARCHAR(255);

-- food_entries table
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS coach_feedback TEXT;
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS classification VARCHAR(255);
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS chat_starter VARCHAR(255);
