-- goals table
ALTER TABLE goals ADD COLUMN IF NOT EXISTS coach_viewed BOOLEAN DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS created_by_coach BOOLEAN DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS deleted_by_client BOOLEAN DEFAULT FALSE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;

-- users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS coach_id BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS current_weight DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_weight DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS height_cm DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_level VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS primary_goal VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;

-- food_entries table
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS coach_feedback TEXT;
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS classification VARCHAR(255);
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS chat_starter VARCHAR(255);
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS deleted_by_client BOOLEAN DEFAULT FALSE;
ALTER TABLE food_entries ADD COLUMN IF NOT EXISTS description TEXT;

-- notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    related_id VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE notifications ALTER COLUMN message TYPE TEXT;
ALTER TABLE checkins ALTER COLUMN note TYPE TEXT;
ALTER TABLE checkins ALTER COLUMN ai_feedback TYPE TEXT;
ALTER TABLE goals ALTER COLUMN coach_feedback TYPE TEXT;
ALTER TABLE ai_chats ALTER COLUMN content TYPE TEXT;
